# @TODO Add color scheme support
# @TODO Add multilanguage support

languageCode: "es"

header:
  layout: "hybrid" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  showTitle: true

footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

# config/_default/menus.toml
menus:
  main:
    - name: "Blog"
      pageRef: "/blog"
      weight: 10
    - name: "Categorías"
      pageRef: "/about"
      weight: 20

  footer:
    - name: "Etiquetas"
      pageRef: "/tags"
      weight: 30
    - name: "Sobre mí"
      pageRef: "/about"
      weight: 10

content:
  path: "content"
  home: "_index.md"

  title: "La Matemaga"
  # logo: "img/logo.jpg"
  description: "Este es un sitio hecho para mostrar lo chida que soy."
  copyright: "&copy; 2022 Next.js-Theme-Congo and Congo contributors"

  author:
    name: "Congo"
    image: "/author.jpg"
    headline: "Not your ordinary theme!"
    bio: "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
    links:
      - name: "twitter"
        url: "https://twitter.com/lamatemaga"
      - name: "twitch"
        url: "https://twitch.tv/lamatemaga"
      - name: "youtube"
        url: "https://youtube.com/lamatemaga"
      - name: "github"
        url: "https://github.com/lamatemaga"
      - name: "linkedin"
        url: "https://linkedin.com/in/lamatemaga"
