# @TODO Add color scheme support
# @TODO Add multilanguage support

languageCode: "es"

header:
  layout: "hybrid" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  showTitle: true

footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true

# config/_default/menus.toml
menus:
  main:
    - name: "Eventos"
      pageRef: "/eventos"
      weight: 10
    - name: "Contacto"
      pageRef: "/contacto"
      weight: 20

  footer:
    - name: "Contacto"
      pageRef: "/contacto"
      weight: 30
    - name: "Eventos"
      pageRef: "/eventos"
      weight: 10

content:
  path: "content"
  home: "_index.md"

  title: "La Matemaga"
  # logo: "img/logo.jpg"
  description: "Este es un sitio hecho para mostrar lo chida que soy."
  copyright: "&copy; 2022 Next.js-Theme-Congo and Congo contributors"

  author:
    name: "Congo"
    image: "/author.jpg"
    headline: "Not your ordinary theme!"
    bio: "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
    links:
      - name: "twitter"
        url: "https://twitter.com/lamatemaga"
      - name: "twitch"
        url: "https://twitch.tv/lamatemaga"
      - name: "youtube"
        url: "https://youtube.com/lamatemaga"
      - name: "github"
        url: "https://github.com/lamatemaga"
      - name: "linkedin"
        url: "https://linkedin.com/in/lamatemaga"

params:
  # Contact page
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  email: "xzbkggvw"
